CREATE DATABASE todolist;

CREATE USER 'dev'@'localhost' IDENTIFIED BY 'devpass' ;
GRANT SELECT, INSERT, UPDATE, DELETE ON todolist.* TO 'dev'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE users(
	_id int NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	first_name varchar(255) NOT NULL,
	last_name varchar(255) NOT NULL,
	username varchar(255) NOT NULL UNIQUE,
	email varchar(255) NOT NULL UNIQUE ,
	password varchar(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE projects(
	_id int NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	project_name varchar(255) NOT NULL,
	owner_id int NOT NULL,
	FOREIGN KEY (owner_id) REFERENCES users(_id) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE todos(
	_id int NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
	todo_name varchar(255) NOT NULL,
	todo_description varchar(255),
	type varchar(8) NOT NULL,
	state varchar(8) NOT NULL,
	project_id int NOT NULL,
	FOREIGN KEY (project_id) REFERENCES projects(_id) ON DELETE CASCADE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

